/*
 * An exception can be generated by ne method and caught by another.
 */
public class ExcTest
{
    // Generate an exception
    public static void genException()
    {
        int[] nums = new int[4];

        System.out.println( "Before exception is generated." );

        // generate an index-out-of-bounds exception
        nums[7] = 10;
        System.err.println( "This won't get displayed" );
    }
}
